// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Libirary.DAL.Models
{
    public partial class librarySystemContext : DbContext
    {
        public librarySystemContext()
        {
        }

        public librarySystemContext(DbContextOptions<librarySystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblBook> TblBook { get; set; }
        public virtual DbSet<TblBorrow> TblBorrow { get; set; }
        public virtual DbSet<TblCategory> TblCategory { get; set; }
        public virtual DbSet<TblWriter> TblWriter { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblBook>(entity =>
            {
                entity.HasOne(d => d.BookCategoryNavigation)
                    .WithMany(p => p.TblBook)
                    .HasForeignKey(d => d.BookCategory)
                    .HasConstraintName("FK_tbl_Book_tbl_Category");

                entity.HasOne(d => d.BookWriterNavigation)
                    .WithMany(p => p.TblBook)
                    .HasForeignKey(d => d.BookWriter)
                    .HasConstraintName("FK_tbl_Book_tbl_Writer");
            });

            modelBuilder.Entity<TblBorrow>(entity =>
            {
                entity.HasOne(d => d.Book)
                    .WithMany(p => p.TblBorrow)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK_tbl_Borrow_tbl_Book");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}