// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Libirary.DAL.Models
{
    [Table("tbl_Book")]
    public partial class TblBook
    {
        public TblBook()
        {
            TblBorrow = new HashSet<TblBorrow>();
        }

        [Key]
        [Column("BookID")]
        public int BookId { get; set; }
        [StringLength(250)]
        public string BookName { get; set; }
        public int? BookCategory { get; set; }
        public int? BookWriter { get; set; }
        [Column(TypeName = "ntext")]
        public string BookIntro { get; set; }
        [Column(TypeName = "ntext")]
        public string BookDetails { get; set; }
        public bool? IsAvailable { get; set; }
        public int? AvailableNumber { get; set; }

        [ForeignKey("BookCategory")]
        [InverseProperty("TblBook")]
        public virtual TblCategory BookCategoryNavigation { get; set; }
        [ForeignKey("BookWriter")]
        [InverseProperty("TblBook")]
        public virtual TblWriter BookWriterNavigation { get; set; }
        [InverseProperty("Book")]
        public virtual ICollection<TblBorrow> TblBorrow { get; set; }
    }
}