// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Libirary.DAL.Models
{
    [Table("tbl_Borrow")]
    public partial class TblBorrow
    {
        [Key]
        [Column("BorrowID")]
        public int BorrowId { get; set; }
        [Column("BookID")]
        public int? BookId { get; set; }
        [StringLength(250)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        [Column("UserNationalID")]
        [StringLength(250)]
        public string UserNationalId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BorrowFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BorroTo { get; set; }
        public double? BorrowPrice { get; set; }
        public double? Penalty { get; set; }

        [ForeignKey("BookId")]
        [InverseProperty("TblBorrow")]
        public virtual TblBook Book { get; set; }
    }
}