// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Libirary.DAL.Models
{
    [Table("tbl_Category")]
    public partial class TblCategory
    {
        public TblCategory()
        {
            TblBook = new HashSet<TblBook>();
        }

        [Key]
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [StringLength(250)]
        public string CategoryName { get; set; }

        [InverseProperty("BookCategoryNavigation")]
        public virtual ICollection<TblBook> TblBook { get; set; }
    }
}